name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installer Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Compiler le projet
        run: |
          mkdir -p bin
          javac -d bin src/SonarHorrorAuth.java

      - name: Analyse SonarCloud
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=66098b46411154c57b56dec30cb2be33e5ccd1d2
            -Dsonar.organization=poun-2108
            -Dsonar.sources=src
            -Dsonar.java.binaries=bin
